/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-roboto)', 'Arial', 'Helvetica', 'sans-serif'],
      },
      fontSize: {
        'caption-2': ['0.625rem', { lineHeight: '0.875rem', fontWeight: '400' }],
        'caption-2-strong': ['0.625rem', { lineHeight: '0.875rem', fontWeight: '500' }],
        'caption-1': ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
        'caption-1-strong': ['0.75rem', { lineHeight: '1rem', fontWeight: '500' }],
        'caption-1-stronger': ['0.75rem', { lineHeight: '1rem', fontWeight: '700' }],
        'body-1': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'body-1-strong': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '500' }],
        'body-1-stronger': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '700' }],
        'body-2': ['1rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'body-2-strong': ['1rem', { lineHeight: '1.375rem', fontWeight: '500' }],
        'body-2-stronger': ['1rem', { lineHeight: '1.375rem', fontWeight: '700' }],
        'subtitle-1': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '500' }],
        'title-3': ['1.5rem', { lineHeight: '2rem', fontWeight: '500' }],
        'title-2': ['1.75rem', { lineHeight: '2.25rem', fontWeight: '500' }],
        'title-1': ['2rem', { lineHeight: '2.5rem', fontWeight: '500' }],
        'large-title': ['2.5rem', { lineHeight: '3.25rem', fontWeight: '500' }],
        'display': ['4.25rem', { lineHeight: '5.75rem', fontWeight: '500' }],
      },
      colors: {
        neutralFg: {
          DEFAULT: '#424242',
          hover: '#242424',
          pressed: '#242424',
          selected: '#242424',
          disabled: '#bdbdbd',
        },
        brandFg: {
          DEFAULT: '#D2DDC1',
          hover: '#A7B495',
          pressed: '#97A681',
          selected: '#B8C3A9',
          link: '#536041',
          linkHover: '#475238',
          linkPressed: '#3C4530',
          linkSelected: '#536041',
        },
        brandFg2: {
          DEFAULT: '#F1F6E7',
          hover: '#F1F6E7',
          pressed: '#DAE7C8',
          selected: '#E6EDDC',
        },
        neutralBg: {
          0: '#FFFFFF',
          DEFAULT: '#fafafa',
          hover: '#f0f0f0',
          pressed: '#dbdbdb',
          selected: '#e6e6e6',
          disabled: '#f0f0f0',
          level2: '#ffffff',
          level2Hover: '#f5f5f5',
          level2Pressed: '#e0e0e0',
          level2Selected: '#ebebeb',
          level3: '#f5f5f5',
          level3Hover: '#ebebeb',
          level3Pressed: '#d6d6d6',
          level3Selected: '#e0e0e0',
        },
        neutralStroke: {
          DEFAULT: '#e5e5e5',
          hover: '#c7c7c7',
          pressed: '#b3b3b3',
          selected: '#bdbdbd',
          disabled: '#e5e5e5',
          level2: '#e0e0e0',
          subtle: '#f0f0f0',
        },
        brandStroke: {
          DEFAULT: '#B8C3A9',
        },
      },
    },
  },
  plugins: [],
  important: true,
};
